name: Friends
version: ${project.version}
main: dev.lightdream.friends.Main
authors: [ L1ghtDream ]
website: https://lightdream.dev
softdepend:
  - LightDreamAPI
commands:
  friends:
    description: NA
  mainmenu:
    description: NA
  party:
    description: NA
  ld-api:
    description: NA